# Generated by Django 4.2.16 on 2024-11-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CCPS.article'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CCPS.project'),
        ),
    ]
