# Generated by Django 4.2.16 on 2024-11-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCPS', '0002_alter_image_article_alter_image_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='img',
        ),
    ]
