# Generated by Django 4.2.16 on 2025-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCPS', '0003_rename_image_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='count',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
